#! /bin/bash

if [ "$#" -lt 2 ]; then
	echo "o programa $0 requer o nome do arquivo e arquivos a serem compactados"
	exit 1
fi
arquivo_saida="$1"
arquivos=("${@:2}")

for arquivo in "${arquivos[@]}"; do
	if [ ! -e "$arquivo" ]; then
		echo "Arquivo não encontrato: $arquivo"
		exit 2
	fi
done

tar -czf "$arquivo_saida" "${arquivos[@]}"
echo "Compactado com sucesso em $arquivo_saida"
